dist: xenial
language: clojure
lein: 2.9.1
jdk: openjdk11
addons:
  chrome: stable
  apt:
    sources:
      - google-chrome
    packages:
      - chromium-browser
      - chromium-chromedriver
before_script:
  - cd $TRAVIS_BUILD_DIR
  - ./full-prepare.sh
  - ./restart.sh
script: java -jar test/target/test.jar it
